# Generated by Django 4.0.4 on 2022-06-05 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='fechaDePublicacion',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(),
        ),
    ]
