# Generated by Django 4.0.4 on 2022-06-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDePublicacion', models.DateField()),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
    ]
