# Generated by Django 4.0.4 on 2022-06-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaciones',
            old_name='nombre',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='fechaDePublicacion',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='contenido',
            field=models.TextField(),
        ),
    ]
