# Generated by Django 4.0.4 on 2022-06-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_rename_nombre_publicaciones_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='fecha',
        ),
    ]
